version: '3.8'

services:
  app:
    build: .
    container_name: config-logger-app
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/configlogger
      - PORT=4000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: config-logger-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
